### PR TITLE
why isnt this public smh

### PR DESCRIPTION
**Pull request by Nebby1999**
quite literally changed internal to public, lol.

### CODE REVIEW

**Review by harbingerofme — CHANGES_REQUESTED** [review]
The attribute it self doesn't inherently do anything, this is a bit pointless

**Comment by Nebby1999** [comment]
understandable, cant even remember why i wanted it

oh well

**Comment by xiaoxiao921** [comment]
> understandable, cant even remember why i wanted it
> 
> oh well

It put a list of possible arguments for a given ConCommand, the issue with your PR is that changing it to public won't do anything for people that put it in their own commands because the scanner only scan DebugtoolKit assembly right now

**Comment by Nebby1999** [comment]
Ahhh, ok yeah that makes sense...

Might look into this later and actually make it useful for other external commands, but for now i'm too busy doing other things

**Pull request closed without merging**
